<div class="footer__final">
    <div class="footer__final-container">
        <ul class="footer__final-social ui-flex-center">
            <li>
                <a href="#" class="footer__final-link">
                    <span class="icon-Pinterest"><span class="path1"></span><span class="path2"></span></span>
                </a>   
            </li>
            <li>
                <a href="#" class="footer__final-link">
                    <span class="icon-Twitter"><span class="path1"></span><span class="path2"></span></span>
                </a>
            </li>
            <li>
                <a href="#" class="footer__final-link">
                    <span class="icon-Facebook"><span class="path1"></span><span class="path2"></span></span>
                </a>
            </li>
            <li>
                <a href="#" class="footer__final-link">
                    <span class="icon-Instagram"><span class="path1"></span><span class="path2"></span></span>
                </a>
            </li>
            <li>
                <a href="#" class="footer__final-link">
                    <span class="icon-Google_plus"><span class="path1"></span><span class="path2"></span></span>
                </a>
            </li>
        </ul>
        <ul class="footer__final-credit ui-flex-center">
            <li class="card visa"></li>
            <li class="card master"></li>
            <li class="card discover"></li>
            <li class="card amex"></li>
        </ul>
        <div class="footer__final-copyright ui-flex-center">
            <span class="copyright-txt">Copyright © 2012 - 2017 Caskers.&nbsp; </span>
            <span class="copyright-txt"> All rights reserved.</span>
        </div>
    </div>
</div>