<div class="description">
    <div class="description__wrapper">
        <p class="description__txt">
            All sales are solicited, offered, accepted, made and delivered by licensed parties or retailers who
            receive all orders.
        </p>
        <p class="description__txt">
            All alcohol orders are accepted and sold by a New York licensed retailer: Andrew's Wine Cellar, Inc.,
            Bourbon Street Wine & Liquor Warehouse, Gramercy Wine Country, Inc., or Mash + Grape. The seller varies
            by product, and will be identified prior to checkout.
        </p>
    </div>
    <a href="#" class="description__link"
        >Who are Andrew's Wine Cellar, Inc., Bourbon Street Wine & Liquor Warehouse, Gramercy Wine Country, Inc.,
        and Mash + Grape?</a
    >
</div>
