<div class="menu__wrapper">
  <div class="menu">
      <div class="menu__column">
        <h3  class="menu__column-title"><?php echo __('Products')?></h3>
        <ul>
          <li><a href="#"><?php echo __('Spirits')?></a></li>
          <li><a href="#"><?php echo __('Clubs')?></a></li>
          <li><a href="#"><?php echo __('Gif Cards')?></a></li>
        </ul>
      </div>
      <div class="menu__column">
        <h3 class="menu__column-title"><?php echo __('Company')?></h3>
        <ul>
          <li><a href="#"><?php echo __('Our Story')?></a></li>
          <li><a href="#"><?php echo __('Contact Us')?></a></li>
          <li><a href="#"><?php echo __('Feedback')?></a></li>
        </ul>
      </div>
      <div class="menu__column">
        <h3 class="menu__column-title"><?php echo __('Information')?></h3>
        <ul>
          <li><a href="#"><?php echo __('Terms')?></a></li>
          <li><a href="#"><?php echo __('Privacy')?></a></li>
          <li><a href="#"><?php echo __('Shipping')?></a></li>
          <li><a href="#"><?php echo __('FAQ')?></a></li>
          <li><a href="#"><?php echo __('Invite a Friend')?></a></li>
          <li><a href="#"><?php echo __('For Offices')?></a></li>
        </ul>
      </div>
      <div class="menu__column">
        <h3 class="menu__column-title"><?php echo __('Invite a friend')?></h3>
        <p>
          Share your custom link below and earn credits. 
          You'll receive a $10 credit whenever your friends place their first orders. 
          Invite them today!
        </p>
        <input class="footer__input" type="text" value="https://www.caskers.com/?ref=MDoyOjRoFqE" />
        <ul class="footer__links-social">
          <li>
            <a href="#">
              <span class="icon-fb"><span class="path1"></span><span class="path2"></span></span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="icon-tw"><span class="path1"></span><span class="path2"></span></span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="icon-ins"><span class="path1"></span><span class="path2"></span></span>
            </a>
          </li>       
          <li>
            <a href="#">
              <span class="icon-g"><span class="path1"></span><span class="path2"></span></span>
            </a>
          </li>       
          <li>
            <a href="#">
                <span class="icon-pin"><span class="path1"></span><span class="path2"></span></span>
              </a>
          </li>       
          <li>
            <a href="#">
              <span class="icon-mail1"><span class="path1"></span><span class="path2"></span></span>
            </a>
          </li>       
        </ul>
      </div>
  </div>
</div>